# Generated by Django 3.2.5 on 2021-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalyzer', '0002_auto_20210803_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='positivity_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
