# Generated by Django 3.2.5 on 2021-08-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsanalyzer', '0003_auto_20210809_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='record_type',
            field=models.IntegerField(null=True),
        ),
    ]
